server:
  port: 8095
selfcloud-chat:
  uuid:
    salt: ${UUID_SALT:4ytS5hJtwH4YMp1PBdH1bOxq8RaVUDkMB8kbBgc5cbCmFBj)zQIQ0f?Ism!Q(fBZ}
  security:
    host: ${SECURITY_HOST:localhost}
selfcloud-security:
  jwt:
    #TODO
    secret-key: ${JWT_SECURITY_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-time: 3600000
logging:
  level:
    org.springframework.security: debug
    org.springframework.web.socket: debug
    org.springframework.orm.jpa: INFO
    org.hibernate.SQL: DEBUG
    io.eventuate: DEBUG
    io.eventuate.tram: DEBUG

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  h2:
    console:
      enabled: true
  application:
    name: selfcloud-chat
  datasource:
    username: ${CHAT_DB_USERNAME:chats}
    password: ${CHAT_DB_USERNAME:chats}
    url: jdbc:mysql://${SECURITY_HOST_IP:localhost}:3306/chats
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  flyway:
    enabled: true

springdoc:
  show-login-endpoint: true
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    serviceUrl:
      defaultZone:  http://${EUREKA_HOST:localhost}:8761/eureka
  instance:
    prefer-ip-address: 'true'
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${KAFKA_HOST:localhost}:9092
  zookeeper:
    connection:
      string: ${ZOOKEEPER_HOST:localhost}:2181

eventuate:
  transactional:
    messaging:
      kafka:
        replication: 1
